TerminalId: 1
TerminalName: "Node1"
#TerminalIP: ""
TerminalPort: 8888
#-----------------------------------
BroadcastTxPort:    "9999"
BroadcastTxIP:      "255.255.255.255"
##----------------------------------
BroadcastRxPort:    "9999"
BroadcastRxIP:      ""
#-----------------------------------
UnicastRxPort:      "8888"
#UnicastRxIP:        "239.83.100.109"
UnicastRxIP:        "239.0.0.0"
UnicastTxPort:      "8888"
#----------------------------------
DroneConnTimer: 5
DroneLogPath: "C:/Users/GS31342/go/log/"
#GroundIPandPort: "172.17.45.2:8888"
#GroundIPandPort: "10.0.1.236:8888"
## ========================================