version: '3.5'
networks:
  TB-NETWORK:
    name: TB-NETWORK
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: wwwserver
    container_name: TB-WWWSERVER
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./www:/var/www
      - /Users/scuric/go/testbed/log:/log
      - /Users/scuric/go/testbed/proj:/proj
    links:
      - mysql
    networks:
      - TB-NETWORK
    environment:
      DB_HOST: TB-MYSQLSERVER
      DB_DATABASE: tbdb
      DB_USERNAME: scuric
      DB_PASSWORD: 
  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: tbdb
      MYSQL_USER: scuric
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD: 
