#! /bin/sh

SERVER=${SERVER:-"172.18.0.2"}
SHARE=${SHARE:-"/exports"}
FOLDER=${FOLDER:-""}
MOUNT_POINT=${MOUNT_POINT:-"/mnt/cache"}
MOUNT_OPS=${MOUNT_OPS:-"-o vers=3"}

if [ $# -gt 0 ]
then
  # first argument is the custom docker command shell provided by plugin
  # second argument is the java command line generated by the plugin (passed as a single arg)
  shift
  export
  /sbin/rpcbind -w &
  mount -t nfs ${MOUNT_OPS} ${SERVER}:${SHARE}/${FOLDER} ${MOUNT_POINT}
  exec /bin/sh -c "$@"
fi

